# Generated by Django 5.0.6 on 2024-07-02 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCB', '0002_aout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aout',
            options={'managed': False, 'ordering': ('product_name', 'workweek')},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'managed': False, 'ordering': ('product_name', 'due_date', '-quantity')},
        ),
    ]
