# Generated by Django 5.0.6 on 2024-07-02 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCB', '0003_alter_aout_options_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'managed': False, 'ordering': ('priority', 'due_date', '-quantity')},
        ),
    ]
