# Generated by Django 5.0.6 on 2024-08-08 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCB', '0004_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aout',
            table='aout',
        ),
    ]
