# Generated by Django 5.0.6 on 2024-07-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aout',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('workweek', models.IntegerField(db_column='Workweek')),
                ('product_name', models.CharField(db_collation='Chinese_Taiwan_Stroke_CI_AS', db_column='Product Name', max_length=10)),
                ('quantity', models.IntegerField(db_column='Quantity')),
            ],
            options={
                'db_table': 'AOUT',
                'managed': False,
            },
        ),
    ]
